### PR TITLE
Error prevention edits and formatting

### PR DESCRIPTION
**Pull request by gradualclearing**
Minor edits to remove credits and scoring and fix code example formatting.

### CODE REVIEW

**Review by michael-n-cooper — APPROVED** [review]

**Review by a11ydoer — DISMISSED** [review]

**Comment by michael-n-cooper** [comment]
@gradualclearing I merged main into this branch in order to resolve merge conflicts. I'm not fully sure that methods/required-inputs-indicated/examples.html wound up the way you intended, please check that and leave an approving review if it's good so I can merge.

**Comment by gradualclearing** [comment]
@michael-n-cooper you're right, it looks like there are still issues with the markup. Let's not merge methods/required-inputs-indicated/examples.html for now.

**Comment by gradualclearing** [comment]
@michael-n-cooper Can we leave this PR open for now? We have more edits to do to respond to the latest survey.

**Comment by gradualclearing** [comment]
@a11ydoer I've completed the updates from the [Google Doc](https://docs.google.com/document/d/1s-wx57F_p1V-ndalMgBjQUZkQU6zN7dnenTx112_C0I/edit#). Please have a look and make any necessary changes. Thank you!

**Review by colabottles — DISMISSED** [review]

**Review by a11ydoer — APPROVED** [review]
@jspellman @gradualclearing @michael-n-cooper 
This looks good.

**Review by colabottles — APPROVED** [review]

**Pull request merged**
