### PR TITLE
Visual contrast

### PR DESCRIPTION
**Pull request by michael-n-cooper**
Remove guideline for visual contrast of text, related content, and early draft methods.

### CODE REVIEW

**Comment by Myndex** [comment]
Only this commit:

> _remove old draft methods...a8089d1_

Solves the issues I've brought up previously, the materials that were never intended to be public facing.

All of the other commits removes materials that should not be removed, only UPDATED, and the updates are in pull request #630.

Why is visual contrast being deleted here?

Regards,

Andrew.

**Review by jspellman — APPROVED** [review]
I checked that the files being deleted are the prototypes and that we are not losing any current work.

**Comment by jspellman** [comment]
@Myndex, these pages are old prototypes. That is the reason we kept missing them when marking pages as deprecated. They can be deleted. We are not removing Visual Contrast of Text from WCAG3 in this PR, just some old prototype pages that are causing confusion.

**Comment by Myndex** [comment]
@jspellman 

Thank you Jeanne, that wasn’t clear. I agree the old “pink” prototypes should be deleted as they have been causing actual problems. Some of the others “appeared” to be current working drafts.

With that said, PR #630 is a set of updates for visual contrast, intended for the current draft. I am now concerned that PR is not pointing to the correct files. It is not clear I this repo which files are related to the current draft.

**Comment by jspellman** [comment]
@Myndex the position of the files is the key.  Any of these files in a /guidelines folder (in a subfolder) are a prototype. The current files are located in the /methods or /how-tos at the same level as the /guidelines

**Comment by Myndex** [comment]
Hi @jspellman and also @michael-n-cooper 

> _the position of the files is the key. Any of these files in a /guidelines folder (in a subfolder) are a prototype. The current files are located in the /methods or /how-tos at the same level as the /guidelines_

### That is my understanding as well.

The _FIRST THREE_ commits above are **NOT** in the prototypes /guidelines folder nor a subfolder. The _FIRST THREE_ commits are at the **top level, /methods or /how-tos,** meaning the current draft, as I understood it, and as you just described.


## _THESE COMMITS ARE TOP LEVEL_
[remove visual-contrast-of-text how-to d0ca892](https://github.com/w3c/silver/pull/663/commits/d0ca892da6778d03e7f1d0505a41f4ea003c545b)

[Delete luminance-contrast-between-background-and-text.html b7af6cb](https://github.com/w3c/silver/pull/663/commits/b7af6cb4eda845d646fd00df28ab5e465ba70886)

[remove font-characteristics-contrast method ea1a2bc](https://github.com/w3c/silver/pull/663/commits/ea1a2bc2c9242b20d5b3aee8dd995aead6ae5370)

I object to these commits.

Instead, PR #630 should be applied as indicated below.


## _THESE COMMITS ARE PROTOTYPE OR LOWER_
[remove visual contrast of text guideline 1643dc2](https://github.com/w3c/silver/pull/663/commits/1643dc27080c505114493a8939ac6c3a5275a7e0)

[remove old draft methods  a8089d1](https://github.com/w3c/silver/pull/663/commits/a8089d1222990f975ad32feb35af6a6d3d0af4a5)

I agree these commits remove objectionable and confusing materials.

I have been attempting to have them removed or marked as deprecated for two years, starting with PR #213. Thank you for removing them.


## _PENDING PR #630_ 
And I just confirmed that my pending PR #630 addresses the **top level how-tos and methods**, as intended, and which have been peer-reviewed by W3C Staff Technical Director Chris Lilly and approved therein as indicated, awaiting merging.

Thank you for reading

Andy

**Comment by Myndex** [comment]
What is the status of this pull request please?

**Comment by michael-n-cooper** [comment]
Exploratory content that does not gain WG support to proceed to the next stage within 6 months is automatically removed in the [WCAG 3 development process](https://www.w3.org/WAI/GL/wiki/Maturity_Labeling_Process). We still hope the promising contrast work will continue to mature for potential later inclusion.

**Comment by Myndex** [comment]
Adding a note here to clear up some confusion, as this PR is being linked to and is causing misunderstandings. The legacy versions of APCA that were removed per this PR, were all **_early versions that were very obsolete_**. Having them here was creating confusion.

APCA and the related guidelines are still in process in terms of development and refinement. Because of the complicated nature of visual contrast, the development is continuing somewhat separately with [IRT](https://readtech.org/ARC/), and we have an [**open discussion forum**](https://github.com/Myndex/SAPC-APCA/discussions) here on GitHub.

**Pull request merged**
