### PR TITLE
don't autogenerate conformance

### PR DESCRIPTION
**Pull request by michael-n-cooper**
Respec does its own thing with <section id="conformance">. Removing the id removes that trigger and allows us to have our own section. I added the content Respec would normally add, about RFC2119.

### CODE REVIEW

**Comment by michael-n-cooper** [comment]
Note Respec will warn about no section id="conformance", but we gotta just ignore that warning, we get valid output this way.

**Review by bruce-usab — CHANGES_REQUESTED** [review]
Can "authoring guidelines" be replaced with "authoring guidance" or some other word that is _not_ guidelines?

With previous drafts, throughout the abstract and elsewhere, lower-case-g "guidelines" refers to the specification as a whole, the G in WCAG.

Also, "informative" or "informative (non-normative)" is used previously instead of just "non-normative" and that seems more like plain language to me.

**Comment by michael-n-cooper** [comment]
@rachaelbradley I changed the "as well as" to "in addition to". @bruce-usab I removed "authoring guidelines". Both were taken from stock Respec conformance text, but the reason this PR overrides that is so we can customize.

**Review by rachaelbradley — CHANGES_REQUESTED** [review]
The Normative section and 4. Conformance content is very repetitive. Can we consolidate or otherwise deduplicate these?

**Comment by michael-n-cooper** [comment]
OBE, better to start fresh.

**Pull request closed without merging**
