### PR TITLE
Moved system over to use Jekyll for semi-CMS type system.

### PR DESCRIPTION
**Pull request by mikecrabb**
Update to the Flavor prototype that uses [Jekyll](https://jekyllrb.com/) to do some more complex things with this (mostly templating). Also changed styling of site and:

- Added in breadcrumbs to assist in navigation
- Added in more content so that we can test with more than 1 SC
- Added in Project Phases (instead of "Roles") based on the stages on the [W3C Start with Accessibility Wiki Page](https://www.w3.org/WAI/EO/wiki/Start_with_Accessibility#Project_Closure)

Note - I don't know how Jarvis feels about Jekyll inside of a folder within a repository. I'm hoping that everything will be OK with the GH-Pages render for this but its worth keeping an eye on this after the merge to double check that it does what we expect it to (i.e...not break)

### CODE REVIEW

**Comment by mikecrabb** [comment]
Not Jarvis...travis, sorry.

**Comment by mikecrabb** [comment]
Yup, this broke quite badly...not sure whats happened with the move over to the GH Pages branch. This prototype might need to get hosted on its own repo. I'll have a look tomorrow to see if I can get it working on this one but I'm not sure if it can. In the meantime it can be viewed at the link below:

[https://mikecrabb.github.io/silver_flavor_prototype/](https://mikecrabb.github.io/silver_flavor_prototype/)

**Comment by nschonni** [comment]
I think it is because of using Material Design, but I find the headings with `class=flavor` look like they have input boxes in them.

**Comment by mikecrabb** [comment]
@nschonni , thanks - I see what you mean with them, I think its the outline all the way round that does it. Do you think that if I changed the CSS for them so that it was something more like this link it would be easier?
https://img.shields.io/badge/style-for--the--badge-green.svg?longCache=true&style=for-the-badge

**Pull request merged**
