### PR TITLE
ACT method proposal

### PR DESCRIPTION
**Pull request by WilcoFiers**

### CODE REVIEW

**Review by jspellman — DISMISSED** [review]
NOte that we need to bring in some plain language -- perhaps from Easy Checks or WAI Tutorials  -- but I like this new design.  It's good enough to show AGWG.

**Review by jspellman — COMMENTED** [review]
I'm sorry that there are Explainer changes in this PR.  I am not sure how that happened, but they were probably on my system when I created the branch.  Please ignore them.  You  do not need to accept or merge them.  I'll see if I can move them to the Explainer branch.

**Review by jspellman — APPROVED** [review]

**Comment by jspellman** [comment]
@michael-n-cooper Michael, can you confirm that Wilco has IPR for WCAG3?  The checks are failing for IPR and the details show Wilco's name as the contributor.  

This branch is ready to merge to Main and close.

**Review by jspellman — CHANGES_REQUESTED** [review]
The Explainer index should not be part of the PR.  How do I move it to another branch?

**Review by michael-n-cooper — APPROVED** [review]
I pushed a change to rename the file description.html to introduction.html, since the content had been so edited. With that change it looks good.

**Review by michael-n-cooper — APPROVED** [review]
Upon reviewing #558 I saw that there were overlapping changes from this PR. To reduce conflicts, I have moved structure changes to 558 and left the method proposal here. This pr should be merged after 558.

**Pull request merged**
