### PR TITLE
Error prevention - minor edits

### PR DESCRIPTION
**Pull request by a11ydoer**
minor edits
- remove the word "credit"
- change "may" to "will"

### CODE REVIEW

**Comment by a11ydoer** [comment]
@gradualclearing 

- I created the pull request for the minor edits we discussed. 
- Duplicate word of "method" was already taken care of in PR 538.

Please let me know if I missed any edits.

**Review by michael-n-cooper — CHANGES_REQUESTED** [review]
Most of these edits look good. But a couple revert edits I had made, changing < to &lt;. The reason I did that was so those would render as code samples in the browser, rather than as browser widgets. I assumed that was the intent since they were in <pre><code>, so those would need to be changed back.

**Comment by a11ydoer** [comment]
@michael-n-cooper 
you are right. I updated  < and > with <code>&lt; and &gt;</code>

**Review by michael-n-cooper — APPROVED** [review]

**Review by gradualclearing — APPROVED** [review]

**Comment by jspellman** [comment]
Looks good to me!  Michael, please merge before Thursday so it can be surveyed.

**Comment by gradualclearing** [comment]
Additional minor edits. Please merge before Thursday!

**Comment by gradualclearing** [comment]
@jspellman and @michael-n-cooper, we did a few more edits. It would be great if they could be merged before the survey goes out. Thank you!

**Comment by jspellman** [comment]
They look good to me.

**Comment by michael-n-cooper** [comment]
This pull request is closed and the branch deleted. Please submit the edits as a new pull request.

**Comment by gradualclearing** [comment]
> This pull request is closed and the branch deleted. Please submit the edits as a new pull request.

I restored the branch before doing the edits. Does that work?

**Comment by gradualclearing** [comment]
@michael-n-cooper I created a new pull request. Let me know if that doesn't do the trick!

**Pull request merged**
