### PR TITLE
Issue severity subgroup pre-TPAC content

### PR DESCRIPTION
**Pull request by fstrr**
Initial PR for the Issue Severity subgroup. Added content to describe our work to date and also what needs to happen next. Also added examples of critical failures to functional images and text equivalent outcomes.

### CODE REVIEW

**Review by cwadamsoforacle — COMMENTED** [review]
I reviewed the 3 files in this PR, and do not have any changes to recommend.  I approve of these.

**Review by cwadamsoforacle — APPROVED** [review]
I approve of these changes.

**Review by rachaelbradley — APPROVED** [review]

**Comment by shawnthompson** [comment]
@rachaelbradley Why were these changes removed?

cc/ @fstrr, @gradualclearing, @alastc

**Comment by alastc** [comment]
>  Why were these changes removed?

This branch was merged, only sub-group members edited it (from the links above), I'm not sure what you mean was removed?

**Comment by shawnthompson** [comment]
Our changes are no long in the [editor's draft](https://w3c.github.io/silver/guidelines/).

They were removed in this commit https://github.com/w3c/silver/commit/0bde7a7f9ac9f4320b4c04b1d25907f7fabc0cc0

@rachaelbradley is adding them back in this PR: [Move issue severity work into main guidelines document #661](https://github.com/w3c/silver/pull/661).

Although the [expected results additions](https://github.com/w3c/silver/pull/656/files#diff-398e06eaa01d8afc9a226b8ce85c0bd48fdcf3d6c8f790f9a9264f79667f148eL40) are not being added back.

**Pull request merged**
