### PR TITLE
important correction: WCAG 3 not Web Content...

### PR DESCRIPTION
**Pull request by slhenry**
Web Content Accessibility Guidelines 3.0 -> W3C Accessibility Guidelines 3.0

### CODE REVIEW

**Comment by michael-n-cooper** [comment]
I treated this as editorial and put it into the pending publication.

**Comment by bruce-usab** [comment]
I am trying to find the bit about the <q>3 being silent</q> in the press release.  No luck so far.

Good job everyone!

**Comment by slhenry** [comment]
Hi @bruce-usab 

Here's what we say about it: https://www.w3.org/WAI/standards-guidelines/wcag/wcag3-intro/#wcag-3-name-formerly-silver-project

Do you think we want to say more? Suggestions for improvement welcome! Here's the GitHub Repo for that page: [New Issue](https://github.com/w3c/wai-intro-wcag/issues/new) , [Edit for Pull Request](https://github.com/w3c/wai-intro-wcag/edit/master/content/wcag3-intro.md)

**Comment by bruce-usab** [comment]
No need to say more, perfect as is!

FWIW, we have updated [our news post](https://www.access-board.gov/news/2021/01/21/w3c-publishes-working-draft-of-the-web-content-accessibility-guidelines-wcag-3-0/).

**Pull request merged**
