### PR TITLE
Fixes for issues

### PR DESCRIPTION
**Pull request by rachaelbradley**
#422

### CODE REVIEW

**Comment by detlevhfischer** [comment]
This is a [rendered version of the changed Method](https://raw.githack.com/w3c/silver/6b55a30db783fb4d3fdf0d82b0c8702441df6f52/methods/clear-words/tests.html).

**Comment by detlevhfischer** [comment]
I see some issues with this method. The most fundamental concern is the reference to a tool that seems to have grown out of a frequently ironic web comic, [blog.xkcd.com](https://blog.xkcd.com/). I would not assume that the tool can and should be used at face value or seen as a blueprint example for tools that are fit for purpose. 

I would also argue that there is a long history if creating simplified vocabularies, a notable one being Ogden's Basic English (850 words there), and that it is not at all clear that the reduction of vocabulary can impove understanding if understanding is not only measured by the share of words understood in themselves by the reader, but also by assessing to what extent information content overall is conveyed correctly and without distortion and possibly misleading simplifications.

The reference to "click" in "uses common words and defines unusual words in one click and one click return" needs to be abandoned in favor of a more generic phrasing of activation and return to the point of regard (which may also happen through pressing ESC, for example). So the test procedure itself seems too restrictive ahd should be revised before accepting the PR.

What also seems missing in the test procedure is the option of passing the test by unpacking a complex or technical term in an explanation in simler terms in brackets after the technical term - surely easier than explanation in some popup. or by shunting users away to some glossary.

**Comment by maryjom** [comment]
IBM had similar comments on the Silver draft regarding the suggested tool (similar to what @detlevhfischer mentions above). I began to think about software product documentation that could be very domain-specific and technical in nature. Some software is used in very specific domains (like security, networking, server management) where someone who works in that field would be super-familiar with terms and language that the average population of people would think is jargon.  This tool would likely highlight virtually all of the content other than conjunctions, prepositions and pronouns.

In an experiment with the referenced tool, I had tried copying language from the Silver draft itself to be analyzed and virtually every noun is flagged as not being in the "common words". Having to define each and every one of them is probably not what this requirement should be recommending.  

An author of content would always wonder just how far the simplification really needs to go. It is far less likely that a tool is a good idea to recommend as I don't think any are capable of identifying or simplifying the information well. Examples I've seen often wind up changing the meaning and having to be very carefully reviewed and corrected after any tool is used.

**Comment by johnfoliot** [comment]
Re: Issues #447 & #464

I specifically object to the closing of these issues because the responses are not sufficiently addressing the substance of those comments:

- "...**the guideline should be documenting the criteria to be met** so people can in turn determine if they are going to buy a tool or add the functionality to tools they currently use." ([Oracle - Issue #464](https://github.com/w3c/silver/issues/464))
- "... Instead of recommending a specific tool, **WCAG should specify the criteria that should be tested.**" ([ITI - Issue #447](https://github.com/w3c/silver/issues/447))

Closing those 2 issues as simply 'concerns related to the proposed tool' misses the larger concerns raised by those commenters.

---------

At this time I also object to continuing to work under the presumption that the proposed "Clear Words" requirement, as currently authored, is worth pursuing further. The [existing draft section](https://w3c.github.io/silver/guidelines/#clear-words)  is currently tagged as "[Exploratory](https://w3c.github.io/silver/guidelines/#section-status-levels)", which according to our [newly adopted Process](https://www.w3.org/WAI/GL/wiki/AG_process#Labeling_Documents) and the current working draft definition of those tagging terms means, "_Feedback should be about the proposed direction._"

My reasons for objecting here then are **about the direction we are taking** with this Requirement, and are as follows:

### Un-tested and unproven:

What evidence do we have that a limited or constrained vocabulary list of the author's choosing will benefit accessibility? I have been working under the assumption that our Requirements would be [data-informed and evidence-based](https://www.w3.org/TR/wcag-3.0-explainer/#ContentGoals) where possible.

While words and word-choice are always important, multiple entities have previously tried to address the broad topic of plain language, readability, and comprehension, with notable examples being the US Federal Government's [plainlanguage.gov](http://plainlanguage.gov/), the [European Union](https://ec.europa.eu/info/departments/translation/clear-writing-for-europe_en), and [ISO](https://www.iso.org/standard/78907.html). 

These efforts frequently relate to existing legislation, yet none provide a mechanical means of testing to ensure the legally mandated goals are met. It is unclear at this writing how the W3C and this Working Group can or will surpass the existing efforts that have come before us, and specifically, if a constrained list of words DID benefit readability and comprehension, why wouldn't this requirement have already added it to the 'plain language' list of requirements in any of these other efforts?


### "Test Tools: Use a common word list for your language. The list should be at least 3000 words long.":

As currently authored, this Requirement demands the author provide a list of a minimum of 3000 words, but does not set a maximum. 

This leaves open the very real possibility that a content author could load in "Merriam Webster's Dictionary" as their list of words (nothing currently forbids that, and Google tells me that "Webster's Third New International Dictionary, Unabridged, together with its 1993 Addenda Section, includes some 470,000 entries.") and then, **using the mystery tool we still have not vetted**, the author could then easily pass the requirement, because every word the author used would (presumably) already be in the dictionary. 

Additionally, the current draft suggests that this newly proposed Requirement is based on feedback from the COGA Task Force, which is currently referenced in the [Editor's Note](https://w3c.github.io/silver/guidelines/#issue-container-generatedID-5), which also states "The selection of user needs and the outcomes necessary to address them is aligned with the new COGA publication, [Making content usable for people with cognitive and learning disabilities [coga-usable]](https://www.w3.org/TR/coga-usable/)." 

Yet there is nothing in the "Making Content" document that suggests that a controlled vocabulary list (no less than 3000 words, no greater than infinity) provides any specific benefit; the closest that document comes is when it describes Outcome # 3.3.1 Clear Language (Written or Audio) (User Story) which provides the following:

"_As a user with a language, processing, or memory impairment, I need the language used to be clear and easy for me to understand so that I can understand the content._

_This user story also includes the following user needs:_

- _I need to understand the language used, including vocabulary, syntax, tense, and other aspects of language._
- _I need to easily distinguish the content from the background distractions._
- _I need words to include accents, characters, and diacritics that are necessary to phonetically read the words. This is often needed for speech synthesis and phonetic readers in languages like Arabic and Hebrew._
- _I need to understand the meaning of the text. I do not want unexplained, implied or ambiguous information because I may misunderstand jokes and metaphors._
- _I need an easy to understand, short summary for long pieces of content or an option for an easy to understand language version._
- _I need images, diagrams, or video clips to help me understand ideas (more than a lot of words)._
- _I need explanations of implied or ambiguous information, like body gestures and facial expressions seen in images and animations._"

It is unclear to this observer how using a list of 3000 words or more addresses any of the above user-needs, especially since according to the current draft, the list of words is first provided by the author (self-certification?).


### Verb tenses, alternate spellings, and other internationalization concerns:

Using an overly simplistic word list has no evidence that it benefits accessibility that I am aware of, but demanding a fixed list ***from the author*** will also potentially MISS more often than HIT  when it comes to the conjugation of verb tenses (especially with Romance languages like French, where in at least French every verb has 6 different ways of being conjugated: Je, Tu, Il/Elle, Nous, Vous, Ils/Elles), or alternate spellings in the same language (living in Canada, I write colour and honour because that is the correct spelling - in Canada), but it can be even more nuanced than that (analyze / analyse, or theater / theatre). 

There is also the issue of fault tolerance: what happens when an author needs to use a word or term that is not on the approved control list (perhaps a foreign language term)? How will this work with, and what is the impact on, testability of [multi-language content](https://blog.duda.co/multi-language-website-examples) on the same screen/view?

It is also worth noting that there does not appear to be an existing example list, and the work effort to develop such a list that addressed verb conjugations and alternate spellings for multiple languages is a non-trivial task that many entities will resist (see: [undue burden](https://www.section508.gov/buy/determine-ict-exceptions/#5)). If we cannot create such a list ourselves as Subject Matter Experts (my presumption today is that we would fail), it is unclear how non-experts would be able to do better.

It also seems to leave no room for 'other' words that an author may need or want to use (including foreign words that most likely would not be part of a regular list of 3000+ words in the author's native language), and I personally have a very real concern that smaller content authors will be unable to meet this proposed requirement without a pre-produced list of words (unless we accept Merriam Webster's Dictionary).

The current Requirement very much feels like an attempt to prove something that cannot be proven, and we should spend real time discussing and examining the viability of this before responding to the commenters in GitHub.

Given the serious concerns related to "Clear Words" at a higher level however, and repeating the initial statement from ITI in [Issue #447](https://github.com/w3c/silver/issues/447),

> "_**Guidelines need to be testable/measurable based on normative information. In some new guidelines such as 7.2 Clear Words this does not appear to be testable based on normative information**_"

...I would rather the Working Group have a robust discussion on the substance of this requirement first: I personally feel our time would be better spent addressing the real concerns related to this proposed requirement, as opposed to just moving things around, merging similar issues in GitHub (for what reason?) and sending back the comment: "_We've done nothing substantive with your comment except group it with another one from 14+ months ago..._"

**Review by michael-n-cooper — APPROVED** [review]

**Pull request merged**
